language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
  - secure: W+NFrU1ziVRtLCFehViJdlO66Peg0fOko0FmnOZJ8vMxnS2OTccOV8plNDx/+ikQuG+0Bpr3PHP8l/zhQ45lOSPW+QgE9k+nY9x7bqtv9pHp9tDDm5otn41DT/kxq1ZyRKn8ZasWg6AQkQ3ISNWAQ3/p7dPMjeIwunvWNNoXw6JRlREJ8ayoXZdI9V58NAFwxElnbEHurclSErArAVISHpB7wV0SQuINi3l3Rv7Qq9xNSNY2dmZwLBB2PPZfRYfABF5iHAYX8UL0cammyWR3iDFEZDQ0lNv36/dwH3t6IT8szr5CZ099k7l1YywZEE+/fgaca9ZL3ILjm8EmJnZJlluTSk+plbrwCwndwDY808bNrgXq9zJ5Kaaxd/eJRWe9ybBtHaII6sVx3MizEwODSHtIJfIBPfaZfv86E/FVmky7ixTnTAjslG/69X0bGMB6PesBn9xgH+KDeOrd0Du14Qy3zPKgx4X5uO7OGYyEDj3sA5EsHFvdvuTeV7oc5fs0jRlKnyBHutZ0kNMfGp77bRlCU6NlkDLywH6+8MtD03W/oKWDgUCQA2d/tPFSr60leX/OAbgF8gDoMLPynzF8hJppWlNLqESI2SaYewNd2czP5X6TbM+o6NTQn8LFRurz6cXk/N+/H7njt+6M1ahoYUQtZb3x0Q11+7LFSmpf5H8=
  - secure: k5GDK1LS0vpBs7EBHL+3/WMnJn07iP+40CT78lsojHtyJm/CTCcHxS6G2xmymLj479HUhFTf3iOMnkaKOL1O57oPX4Zprrr3WN7Igib9NUFRrzzGuY8nrwkHn2vm2vzvt4K0rjWYZNFQ+IGsJ52YgJ+Wc7/rF6xzbphdWLiDUnLam5M8Lu2fBGATd2jzE28x82H+GugJO1NCyinKHWf4nkboOBz0odlv49Hzlzc2dxQ7ilMteZ9l3mVWHePx4kPDgWH84XJjFix4PjZ46WCSHKyJQ1KQvvK8v39vXX4Ab4xstaN5nsZe2NRio/P9dPK48p30A4irVLTghHhYtp4Kp3pChgz5rm/h0IpWTUFo2yUY9MusEup30/V7l3INRi17M+jN14gzYMDwgT2fHdD/R13vgJjWjn+vKI4EvX4Vp3I6oKcfYcaPrb1en/64RdcNooMAB5Wu48OK0N+hduhvN7ofIbrQorDv0NjJT7lP4Iz920ggR7K1K5i0jPYYDn8PzSRyUoD86trAaTVGe4RXbzeKy24fVKEa9/lj0d/AouOmAeYm5gp4F/slRz2dCrCn09kWhYx1u0mEYI1NbPuJHKBbkngM5zhJEHB2YDlTCJcZLEJPllPKewoClC04YeGXAWXsb0f7pJOsNmb37p/b/j6tCQY+plnBivxlOqHPkFA=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
